<expr> ::= (<expr> <bop> <expr>) | <uop>(<expr>) | <var> | <const>
<bop> ::= + | - | * | / | **
<uop> ::= log
<var> ::= X[<varidx>]
<const> ::= C[0] | C[1] | C[2] | C[3] | C[4] | C[5]
<varidx> ::= GE_RANGE:n_vars
