<expr> ::= (<expr> <bop> <expr>) | <uop>(<expr>) | <var> | <const>
<bop> ::= + | - | * | /
<uop> ::= log | sqrt | exp | abs
<var> ::= X[<varidx>]
<const> ::= C[<constidx>]
<varidx> ::= GE_RANGE:n_vars
<constidx> ::= GE_RANGE:n_consts